### ISSUE TITLE
Public transport screen

### ISSUE THREAD

**Issue by mtatko** [CzerwoniakPlus/app#2]
#### TODO:
- [ ] Bottom Tabs Navigator
   - [x] Arrivals near the school
   - [x] Departures near the school
- [x] API connection for retrieving data
- [x] Button redirecting to PKS Nova timetable lookup
